<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Goo" Version="[0.6.3]" GeneratePathProperty="true" ExcludeAssets="all" PrivateAssets="all" />
    <Reference Include="GSharp.Core" HintPath="$(PkgGoo)/tools/gsharp/compiler/GSharp.Core.dll" />
  </ItemGroup>
</Project>
